# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1

# Commands to be run before your environment runs.
before_script:
  - composer require php-coveralls/php-coveralls
  - composer self-update
  - composer install

# Commands you want to run that will verify your build.
script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# Execute another command after success of the script.
after_success:
  - vendor/bin/php-coveralls -v

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always